experiment_name: testing-prompted-metadata
data_path: example_data/histopathology
df_data_dir: null
save_files_dir: null
unconditional_dataset: false
seperate_folder_per_label: false
label_column: label_name